<a href="https://colab.research.google.com/github/AksonovaOlena/MN/blob/main/%D0%90%D0%BA%D1%81%D1%8C%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0_%D0%9B%D0%A0_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [3]:
#1  Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#2 Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.
m_sqr_arr = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print("Матриця розміром 4x4:")
print(m_sqr_arr)

Матриця розміром 4x4:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
#3 Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 5 та виведіть його значення.
matrix = np.random.randint(6,size=(4,4))
print(matrix)

[[4 4 2 2]
 [5 5 3 1]
 [1 4 3 2]
 [0 4 3 0]]


In [20]:
#4 Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення
matrix = np.random.rand(3,3)
print(matrix)

[[0.59192587 0.41651677 0.10116659]
 [0.47307024 0.60148194 0.92458389]
 [0.60123324 0.55138496 0.58636133]]


In [43]:
#5 Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
#  віднімання та множення.
vector1 = np.random.randint(1,21,size=(6))
vector2 =  np.random.randint(1,21,size=(6))
print("Масиви:",vector1,vector2)
print("Додавання:",vector1+vector2)
print("Віднімання:",vector1-vector2)
print("Множення:",vector1*vector2)

Масиви: [17 11 13  9  3 19] [10 13 20 13 17  3]
Додавання: [27 24 33 22 20 22]
Віднімання: [  7  -2  -7  -4 -14  16]
Множення: [170 143 260 117  51  57]


In [69]:
#6 Створіть дві матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх добуток.
a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[5, 6], [7, 8]])
c = np.dot(a,b)
print("Матриці: \n",a,"\n\n",b)
print("\n Добуток матриць:\n",c)

Матриці: 
 [[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]

 Добуток матриць:
 [[19 22]
 [43 50]]


In [81]:
#7 Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix1 = np.random.randint(1,11,size=(3,2))
matrix2 = np.random.randint(1,11,size=(2,4))
m=np.dot(matrix1,matrix2)
print("Матриці: \n",matrix1,"\n\n",matrix2)
print("\nДобуток: \n",m)

Матриці: 
 [[ 7  7]
 [ 7 10]
 [ 2  4]] 

 [[ 1  5  3  6]
 [10  4  8  2]]

Добуток: 
 [[ 77  63  77  56]
 [107  75 101  62]
 [ 42  26  38  20]]


In [84]:
#8 Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.
matrix = np.random.randint(1,8,size=(2,2))
matrix_inv = np.linalg.inv(matrix)
print(matrix)
print("\n",matrix_inv)

[[3 7]
 [1 4]]

 [[ 0.8 -1.4]
 [-0.2  0.6]]


In [92]:
#9 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.rand(3,3)
m_t = matrix.transpose()
print(matrix)
print("\nТранспонована матриця:\n")
print(m_t)

[[0.99534737 0.81541842 0.60360221]
 [0.97867494 0.05466765 0.23212907]
 [0.59516331 0.25337204 0.32311737]]

Транспонована матриця:

[[0.99534737 0.97867494 0.59516331]
 [0.81541842 0.05466765 0.25337204]
 [0.60360221 0.23212907 0.32311737]]


In [107]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.
matrix = np.random.randint(1,11,size=(3,4))
vector = np.random.randint(1,11,size=(4))
m = np.dot(matrix,vector)
print(matrix)
print("\n",vector)
print("\n Добуток: \n",m)


[[ 4  3  5  4]
 [ 8  2  8 10]
 [ 3  1  5  8]]

 [2 1 1 2]

 Добуток: 
 [24 46 28]


In [108]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
#числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
matrix = np.random.randint(1,11,size=(2,3))
vector = np.random.randint(1,11,size=(3))
m = np.dot(matrix,vector)
print(matrix)
print("\n",vector)
print("\n Добуток: \n",m)

[[ 5  7 10]
 [ 2 10  4]]

 [7 7 4]

 Добуток: 
 [124 100]


In [112]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму
matrix1 = np.random.randint(1,11,size=(2,2))
matrix2 = np.random.randint(1,11,size=(2,2))
print("Матриці:\n",matrix1)
print("\n",matrix2)
print("\nСума:\n",matrix1+matrix2)

Матриці:
 [[ 7  6]
 [10  9]]

 [[ 9  1]
 [10  8]]

Сума:
 [[16  7]
 [20 17]]


In [115]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток.
matrix1 = np.random.rand(2,2)
matrix2 = np.random.rand(2,2)
m = np.dot(matrix1,matrix2)
print("Матриці:\n",matrix1)
print("\n",matrix2)
print("\n Добуток:\n",m)

Матриці:
 [[0.5003948  0.09090276]
 [0.19430431 0.56021787]]

 [[0.1005008  0.95522684]
 [0.44643341 0.32665617]]

 Добуток:
 [[0.09087211 0.50768449]
 [0.26962771 0.36860331]]


In [118]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці.
matrix = np.random.rand(5,5)
print("Матриця:\n",matrix)
print("\n Сума:\n",matrix.sum())

Матриця:
 [[0.79831721 0.27764506 0.41366355 0.34158201 0.55162377]
 [0.60171849 0.91873396 0.12711787 0.69872966 0.18820281]
 [0.79921334 0.30701242 0.62321576 0.93734889 0.70997313]
 [0.05116256 0.10911795 0.11225816 0.70855884 0.97453469]
 [0.72698264 0.45017501 0.57299771 0.13321408 0.1290825 ]]

 Сума:
 12.262182060451705


In [125]:
#15 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.uniform(-1,1,size=(3,3))
vector = np.array([matrix[0].sum(),matrix[1].sum(),matrix[2].sum()])
print("Матриця:\n",matrix)
print("\nСума:\n",vector.T)


Матриця:
 [[-0.67266163 -0.63124184 -0.7455255 ]
 [-0.12471159  0.52225187  0.89922005]
 [ 0.89722725 -0.07116932  0.45626698]]

Сума:
 [-2.04942897  1.29676033  1.28232491]
